name: Publish Docker image to GHCR

on:
  push:
    branches: [ "main" ]   # change if you use master or another branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allow pushing to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
